(() => {
'use strict';
const input=document.getElementById('excelFile');if(!input)return;
input.addEventListener('change',event=>{
  const file=event.target.files?.[0];if(!file)return;if(typeof XLSX==='undefined'){alert('تعذر تحميل مكتبة Excel.');return}
  const reader=new FileReader();reader.onload=e=>{try{
    const wb=XLSX.read(e.target.result,{type:'array'}),sheet=(name,header=false)=>wb.Sheets[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],header?{header:1,defval:''}:{defval:''}):[];
    const settingsRows=sheet('Settings',true),raw=Object.fromEntries(settingsRows.slice(1).filter(r=>r[0]).map(r=>[String(r[0]),r[1]])),map={ShippingCostSAR:'shippingCost',BarrelVolumeL:'barrelVolume',BarrelMaxWeightKg:'barrelWeight',OwnerReservedWeightKg:'ownerWeight',OwnerReservedVolumeL:'ownerVolume',PackingReserveWeightKg:'reserveWeight',PackingReserveVolumeL:'reserveVolume',SharesPerBarrel:'sharesPerBarrel',ExpectedBarrelResaleSAR:'barrelResale',SafetyBufferSAR:'safetyBuffer',SharePriceSAR:'sharePrice',SARToSDG:'sarToSdg',MinimumSavingPercent:'minSaving',PickupPoint:'pickupPoint'},settings={};Object.entries(map).forEach(([k,id])=>{if(raw[k]!==undefined)settings[id]=String(raw[k])});settings.autoSharePrice=String(raw.AutoSharePrice??'TRUE').toUpperCase()!=='FALSE';
    const customers=sheet('Customers'),quoteRows=sheet('Quotes'),productRows=sheet('Products'),barrelRows=sheet('Barrels'),customerMap=Object.fromEntries(customers.map(r=>[r.CustomerID,r])),productMap={};productRows.forEach(r=>{(productMap[r.QuoteID]??=[]).push({id:`P-${Math.random().toString(36).slice(2)}`,name:r.ProductName||'',url:r.ProductURL||'',qty:+r.Quantity||1,saudiPrice:+r.SaudiUnitPriceSAR||0,sudanPrice:+r.SudanUnitPriceSDG||0,unitWeight:+r.UnitWeightKg||0,unitVolume:+r.UnitVolumeL||0,barrelId:r.BarrelID||''})});
    const quotes=quoteRows.map(r=>{const c=customerMap[r.CustomerID]||{},cost=+r.CostTotalSAR||+r.TotalSAR||0,offer=+r.OfferPriceSAR||cost;return{quoteId:r.QuoteID||`Q-${Math.random().toString(36).slice(2)}`,customerId:r.CustomerID||`C-${Math.random().toString(36).slice(2)}`,createdAt:r.CreatedAt||new Date().toISOString(),updatedAt:new Date().toISOString(),customerName:c.CustomerName||'',customerPhone:c.WhatsApp||'',recipientName:c.RecipientName||'',recipientPhone:c.RecipientPhone||'',pickupPoint:c.PickupPoint||settings.pickupPoint||'',notes:c.Notes||'',status:r.Status||'جديد',shares:+r.Shares||1,sharesPerBarrel:+r.SharesPerBarrel||+settings.sharesPerBarrel||2,perShareWeightKg:+r.PerShareWeightKg||0,perShareVolumeL:+r.PerShareVolumeL||0,barrelsForQuote:+r.BarrelsForQuote||1,sharePriceSar:+r.SharePriceSAR||0,shippingSar:+r.ShippingSAR||0,productsTotalSar:+r.ProductsTotalSAR||0,totalSar:cost,sarToSdg:+r.SARToSDG||0,offerMode:r.OfferMode||'auto',manualOfferPrice:r.OfferMode==='manual'?String(offer):'',offerPriceSar:offer,offerMarginSar:+r.OfferMarginSAR||(offer-cost),landedTotalSdg:+r.LandedTotalSDG||0,sudanMarketTotalSdg:+r.SudanMarketTotalSDG||0,savingSdg:+r.SavingSDG||0,savingPercent:+r.SavingPercent||0,decision:r.Decision||'',totalWeightKg:+r.TotalWeightKg||0,totalVolumeL:+r.TotalVolumeL||0,defaultBarrelId:r.DefaultBarrelID||'',products:productMap[r.QuoteID]||[]}});
    const barrels=barrelRows.map(r=>({id:r.BarrelID||'',createdAt:r.CreatedAt||new Date().toISOString(),status:r.Status||'تجميع',notes:r.Notes||''})).filter(b=>b.id);
    if(window.BarrelApp?.importData)window.BarrelApp.importData(settings,quotes,barrels);else throw new Error('App import API unavailable');
  }catch(err){console.error(err);alert('تعذر قراءة الملف. استخدم ملف Excel صادرًا من هذا التطبيق.')}};reader.readAsArrayBuffer(file);event.target.value='';
});
})();