(() => {
'use strict';
const $=id=>document.getElementById(id), num=id=>parseFloat($(id).value)||0, integer=id=>Math.max(1,Math.floor(num(id)||1));
const fmt=(v,d=0)=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:d}).format(Number.isFinite(+v)?+v:0);
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const SETTINGS=['shippingCost','barrelResale','safetyBuffer','sharesPerBarrel','sharePrice','sarToSdg','barrelWeight','barrelVolume','minSaving','ownerWeight','ownerVolume','reserveWeight','reserveVolume','pickupPoint'];
const STORE_Q='barrelShare.quotes.v4', STORE_S='barrelShare.settings.v4'; let products=[],editing=null;
const blank=()=>({id:uid('P'),name:'',url:'',qty:1,saudiPrice:0,sudanPrice:0,unitWeight:0,unitVolume:0});
const qs=()=>{try{return JSON.parse(localStorage.getItem(STORE_Q)||'[]')}catch{return[]}};
function setQs(v){localStorage.setItem(STORE_Q,JSON.stringify(v));history();kpis()}
function saveSettings(){const s={};SETTINGS.forEach(x=>s[x]=$(x).value);s.autoSharePrice=$('autoSharePrice').checked;localStorage.setItem(STORE_S,JSON.stringify(s))}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem(STORE_S)||'{}');SETTINGS.forEach(x=>{if(s[x]!==undefined)$(x).value=s[x]});if(s.autoSharePrice!==undefined)$('autoSharePrice').checked=!!s.autoSharePrice}catch{}}
function suggested(){return Math.max(0,(num('shippingCost')-num('barrelResale')+num('safetyBuffer'))/integer('sharesPerBarrel'))}
function cap(){const d=integer('sharesPerBarrel');return{kg:Math.max(0,num('barrelWeight')-num('ownerWeight')-num('reserveWeight'))/d,l:Math.max(0,num('barrelVolume')-num('ownerVolume')-num('reserveVolume'))/d}}
function calc(){const shares=integer('customerShares'),c=cap(),productsSar=products.reduce((s,p)=>s+p.qty*p.saudiPrice,0),sudan=products.reduce((s,p)=>s+p.qty*p.sudanPrice,0),weight=products.reduce((s,p)=>s+p.qty*p.unitWeight,0),volume=products.reduce((s,p)=>s+p.qty*p.unitVolume,0),shipping=shares*num('sharePrice'),total=productsSar+shipping,landed=total*num('sarToSdg'),saving=sudan-landed,pct=sudan?saving/sudan*100:0,kgCap=c.kg*shares,lCap=c.l*shares;const ok=(!products.some(p=>p.unitWeight>0)||weight<=kgCap)&&(!products.some(p=>p.unitVolume>0)||volume<=lCap);return{shares,c,productsSar,sudan,weight,volume,shipping,total,landed,saving,pct,kgCap,lCap,ok,good:sudan>0&&saving>0&&pct>=num('minSaving')&&ok,barrels:Math.ceil(shares/integer('sharesPerBarrel'))}}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderProducts(){const w=$('productsContainer');w.innerHTML='';products.forEach((p,i)=>{const d=document.createElement('details');d.className='product-card';d.open=products.length===1||i===products.length-1;d.innerHTML=`<summary><span>${i+1}) ${esc(p.name||'منتج جديد')}</span><span class="product-summary">${fmt(p.qty)} × ${fmt(p.saudiPrice,2)} ر.س</span></summary><div class="product-body"><div class="form-grid two"><label>اسم المنتج<input data-f="name" value="${esc(p.name)}"></label><label>رابط الشراء<input data-f="url" value="${esc(p.url)}" placeholder="https://..."></label><label>الكمية<input data-f="qty" type="number" min="1" value="${p.qty}"></label><label>سعر الوحدة في السعودية (ر.س)<input data-f="saudiPrice" type="number" min="0" step=".01" value="${p.saudiPrice||''}"></label><label>سعر الوحدة في السودان (ج.س)<input data-f="sudanPrice" type="number" min="0" value="${p.sudanPrice||''}"></label><label>وزن الوحدة كجم — اختياري<input data-f="unitWeight" type="number" min="0" step=".01" value="${p.unitWeight||''}"></label><label>حجم الوحدة لتر — اختياري<input data-f="unitVolume" type="number" min="0" step=".1" value="${p.unitVolume||''}"></label><div style="display:flex;align-items:end"><button class="btn danger" data-del style="width:100%">حذف المنتج</button></div></div></div>`;d.querySelectorAll('[data-f]').forEach(x=>x.oninput=e=>{const k=e.target.dataset.f;p[k]=['name','url'].includes(k)?e.target.value:(parseFloat(e.target.value)||0);render(false)});d.querySelector('[data-del]').onclick=e=>{e.preventDefault();products=products.filter(x=>x.id!==p.id);if(!products.length)products=[blank()];renderProducts();render()};w.appendChild(d)});$('addProductBtn').disabled=products.length>=3}
function whatsapp(){const c=calc(),a=[`السلام عليكم${$('customerName').value.trim()?' '+$('customerName').value.trim():''} 🌹`,'','حسبت ليك الطلب من السعودية إلى ود مدني:',''];products.filter(p=>p.name||p.saudiPrice||p.sudanPrice).forEach((p,i)=>{a.push(`${i+1}) ${p.name||'المنتج'}`,`الكمية: ${fmt(p.qty)}`,`سعر الوحدة في السعودية: ${fmt(p.saudiPrice,2)} ر.س`);if(p.url)a.push(`الرابط: ${p.url}`);a.push('')});a.push(`عدد الحصص: ${fmt(c.shares)}`,`قيمة المنتجات: ${fmt(c.productsSar,2)} ر.س`,`رسوم الحصص: ${fmt(c.shipping,2)} ر.س`,`الإجمالي: ${fmt(c.total,2)} ر.س ≈ ${fmt(c.landed)} ج.س`);if(c.sudan){a.push(`سعر نفس الكمية في السودان: ${fmt(c.sudan)} ج.س`,`التوفير: ${fmt(c.saving)} ج.س (${fmt(c.pct,1)}%)`,'',c.good?'✅ النتيجة: يستاهل الشحن حسب الأرقام الحالية.':c.saving>0?'⚠️ يوجد توفير، لكنه أقل من الحد الذي وضعناه.':'❌ الشراء في السودان أوفر حسب الأرقام الحالية.')}a.push('',`الحساب على صرف: 1 ريال = ${fmt(num('sarToSdg'))} ج.س.`,`سعة الحصة الحالية: ${fmt(c.c.kg,1)} كجم / ${fmt(c.c.l,1)} لتر.`,`الاستلام: ${$('pickupPoint').value}.`,'السعر النهائي يتأكد وقت الشراء وبعد تثبيت شروط شركة الشحن.');return a.join('\n')}
function render(save=true){if(save)saveSettings();const c=calc();$('productsTotalSar').textContent=`${fmt(c.productsSar,2)} ر.س`;$('shippingTotalSar').textContent=`${fmt(c.shipping,2)} ر.س`;$('landedTotalSdg').textContent=`${fmt(c.landed)} ج.س`;$('sudanTotalSdg').textContent=`${fmt(c.sudan)} ج.س`;$('weightLabel').textContent=`${fmt(c.weight,1)} / ${fmt(c.kgCap,1)} كجم`;$('volumeLabel').textContent=`${fmt(c.volume,1)} / ${fmt(c.lCap,1)} لتر`;$('weightBar').style.width=`${Math.min(100,c.kgCap?c.weight/c.kgCap*100:0)}%`;$('volumeBar').style.width=`${Math.min(100,c.lCap?c.volume/c.lCap*100:0)}%`;const box=$('decisionBox');if(!c.ok){box.className='decision bad';box.textContent='⚠️ الطلب يتجاوز سعة الحصص المختارة.'}else if(!c.sudan){box.className='decision neutral';box.textContent='أدخل سعر السعودية وسعر السودان للمنتجات.'}else if(c.good){box.className='decision good';box.textContent=`✅ مناسب — توفير ${fmt(c.pct,1)}%`}else if(c.saving>0){box.className='decision warn';box.textContent=`⚠️ توفير ${fmt(c.pct,1)}% فقط`}else{box.className='decision bad';box.textContent='❌ غير مناسب حسب الأرقام الحالية.'}$('decisionDetails').textContent=c.sudan?`التوفير ${fmt(c.saving)} ج.س · يحتاج ${fmt(c.barrels)} ${c.barrels===1?'برميل':'براميل'}`:'';$('customerSharesHint').textContent=`تقسيم البرميل: ${fmt(integer('sharesPerBarrel'))} حصص · الحصة ≈ ${fmt(c.c.kg,1)} كجم / ${fmt(c.c.l,1)} لتر · طلب العميل يحتاج ${fmt(c.barrels)} ${c.barrels===1?'برميل':'براميل'}.`;$('settingsSummary').innerHTML=`سعة الحصة: <strong>${fmt(c.c.kg,1)} كجم / ${fmt(c.c.l,1)} لتر</strong> · السعر المقترح: <strong>${fmt(suggested(),2)} ر.س</strong>.`;$('whatsappMessage').value=whatsapp();kpis()}
function snap(){const c=calc(),old=editing?qs().find(x=>x.quoteId===editing):null;return{quoteId:editing||uid('Q'),customerId:old?.customerId||uid('C'),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),customerName:$('customerName').value,customerPhone:$('customerPhone').value,recipientName:$('recipientName').value,recipientPhone:$('recipientPhone').value,pickupPoint:$('pickupPoint').value,notes:$('customerNote').value,status:$('quoteStatus').value,shares:c.shares,sharesPerBarrel:integer('sharesPerBarrel'),perShareWeightKg:c.c.kg,perShareVolumeL:c.c.l,barrelsForQuote:c.barrels,sharePriceSar:num('sharePrice'),shippingSar:c.shipping,productsTotalSar:c.productsSar,totalSar:c.total,sarToSdg:num('sarToSdg'),landedTotalSdg:c.landed,sudanMarketTotalSdg:c.sudan,savingSdg:c.saving,savingPercent:c.pct,decision:c.good?'مناسب':c.saving>0?'توفير ضعيف':'غير مناسب',totalWeightKg:c.weight,totalVolumeL:c.volume,products:JSON.parse(JSON.stringify(products))}}
function save(){const s=snap(),q=qs(),i=q.findIndex(x=>x.quoteId===s.quoteId);if(i>=0)q[i]=s;else q.unshift(s);editing=s.quoteId;setQs(q)}
function reset(){editing=null;['customerName','customerPhone','recipientName','recipientPhone','customerNote'].forEach(x=>$(x).value='');$('customerShares').value=1;$('quoteStatus').value='جديد';products=[blank()];renderProducts();render(false)}
function open(id){const q=qs().find(x=>x.quoteId===id);if(!q)return;editing=id;$('customerName').value=q.customerName||'';$('customerPhone').value=q.customerPhone||'';$('recipientName').value=q.recipientName||'';$('recipientPhone').value=q.recipientPhone||'';$('customerNote').value=q.notes||'';$('customerShares').value=q.shares||1;$('quoteStatus').value=q.status||'جديد';products=q.products?.length?q.products.map(p=>({...p,id:p.id||uid('P')})):[blank()];renderProducts();render(false);window.scrollTo({top:0,behavior:'smooth'})}
function history(){const t=$('historySearch').value.toLowerCase(),q=qs().filter(x=>!t||`${x.customerName} ${x.customerPhone} ${(x.products||[]).map(p=>p.name).join(' ')}`.toLowerCase().includes(t)),w=$('historyContainer');if(!q.length){w.innerHTML='<div class="empty">لا توجد عروض محفوظة.</div>';return}w.innerHTML=q.map(x=>`<div class="history-row"><div><strong>${esc(x.customerName||'بدون اسم')}</strong><small>${esc(x.customerPhone||'')}</small></div><div><strong>${fmt(x.shares)} حصة</strong><small>${fmt(x.landedTotalSdg)} ج.س</small></div><div><span class="status ${x.status==='مدفوع'?'paid':x.status==='ملغي'?'cancelled':''}">${esc(x.status)}</span></div><div><strong>${esc(x.decision)}</strong><small>${fmt(x.savingPercent,1)}%</small></div><div class="history-actions"><button class="btn secondary" data-o="${x.quoteId}">فتح</button><button class="btn danger" data-d="${x.quoteId}">حذف</button></div></div>`).join('');w.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>open(b.dataset.o));w.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>setQs(qs().filter(x=>x.quoteId!==b.dataset.d)))}
function kpis(){const q=qs(),active=q.filter(x=>x.status!=='ملغي').reduce((s,x)=>s+(+x.shares||0),0);$('activeSharesKpi').textContent=fmt(active);$('barrelsNeededKpi').textContent=fmt(Math.ceil(active/integer('sharesPerBarrel')));$('quotesKpi').textContent=fmt(q.length);$('sharePriceKpi').textContent=`${fmt(num('sharePrice'),2)} ر.س`}
function exportX(){if(typeof XLSX==='undefined'){alert('تعذر تحميل مكتبة Excel');return}const q=qs(),s=[['الإعداد','القيمة'],['ShippingCostSAR',num('shippingCost')],['BarrelVolumeL',num('barrelVolume')],['BarrelMaxWeightKg',num('barrelWeight')],['OwnerReservedWeightKg',num('ownerWeight')],['OwnerReservedVolumeL',num('ownerVolume')],['PackingReserveWeightKg',num('reserveWeight')],['PackingReserveVolumeL',num('reserveVolume')],['SharesPerBarrel',integer('sharesPerBarrel')],['ExpectedBarrelResaleSAR',num('barrelResale')],['SafetyBufferSAR',num('safetyBuffer')],['SharePriceSAR',num('sharePrice')],['AutoSharePrice',$('autoSharePrice').checked?'TRUE':'FALSE'],['SARToSDG',num('sarToSdg')],['MinimumSavingPercent',num('minSaving')],['PickupPoint',$('pickupPoint').value]],customers=[['CustomerID','CustomerName','WhatsApp','RecipientName','RecipientPhone','PickupPoint','Notes'],...q.map(x=>[x.customerId,x.customerName,x.customerPhone,x.recipientName,x.recipientPhone,x.pickupPoint,x.notes])],qq=[['QuoteID','CustomerID','CreatedAt','Shares','SharesPerBarrel','PerShareWeightKg','PerShareVolumeL','BarrelsForQuote','SharePriceSAR','ShippingSAR','ProductsTotalSAR','TotalSAR','SARToSDG','LandedTotalSDG','SudanMarketTotalSDG','SavingSDG','SavingPercent','Decision','TotalWeightKg','TotalVolumeL','Status'],...q.map(x=>[x.quoteId,x.customerId,x.createdAt,x.shares,x.sharesPerBarrel,x.perShareWeightKg,x.perShareVolumeL,x.barrelsForQuote,x.sharePriceSar,x.shippingSar,x.productsTotalSar,x.totalSar,x.sarToSdg,x.landedTotalSdg,x.sudanMarketTotalSdg,x.savingSdg,x.savingPercent,x.decision,x.totalWeightKg,x.totalVolumeL,x.status])],pp=[['QuoteID','ProductName','Quantity','SaudiUnitPriceSAR','SudanUnitPriceSDG','UnitWeightKg','UnitVolumeL','ProductURL'],...q.flatMap(x=>(x.products||[]).map(p=>[x.quoteId,p.name,p.qty,p.saudiPrice,p.sudanPrice,p.unitWeight,p.unitVolume,p.url]))],c=cap(),dash=[['المؤشر','القيمة'],['عدد الحصص في البرميل',integer('sharesPerBarrel')],['سعة الحصة كجم',c.kg],['سعة الحصة لتر',c.l],['سعر الحصة',num('sharePrice')],['عدد العروض',q.length]];const wb=XLSX.utils.book_new();[['Settings',s],['Customers',customers],['Quotes',qq],['Products',pp],['Dashboard',dash]].forEach(([name,rows])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),name));XLSX.writeFile(wb,`barrel-share-${new Date().toISOString().slice(0,10)}.xlsx`)}
$('addProductBtn').onclick=()=>{if(products.length<3){products.push(blank());renderProducts();render(false)}};$('copyMessageBtn').onclick=async()=>{try{await navigator.clipboard.writeText($('whatsappMessage').value)}catch{$('whatsappMessage').select();document.execCommand('copy')}};$('openWhatsappBtn').onclick=()=>{const p=$('customerPhone').value.replace(/\D/g,''),t=encodeURIComponent($('whatsappMessage').value);window.open(p?`https://wa.me/${p}?text=${t}`:`https://wa.me/?text=${t}`,'_blank')};$('saveQuoteBtn').onclick=save;$('newQuoteBtn').onclick=reset;$('historySearch').oninput=history;$('exportBtn').onclick=exportX;$('importBtn').onclick=()=>$('excelFile').click();$('applySuggestedPriceBtn').onclick=()=>{$('autoSharePrice').checked=true;$('sharePrice').value=suggested().toFixed(2);render()};
SETTINGS.filter(x=>x!=='sharePrice').forEach(id=>{const h=()=>{if(['shippingCost','barrelResale','safetyBuffer','sharesPerBarrel'].includes(id)&&$('autoSharePrice').checked)$('sharePrice').value=suggested().toFixed(2);if(id==='sharesPerBarrel')$(id).value=integer(id);render()};$(id).oninput=h;$(id).onchange=h});$('sharePrice').oninput=()=>{$('autoSharePrice').checked=false;render()};$('autoSharePrice').onchange=()=>{if($('autoSharePrice').checked)$('sharePrice').value=suggested().toFixed(2);render()};$('customerShares').onchange=()=>{$('customerShares').value=integer('customerShares');render(false)};['customerName','customerPhone','recipientName','recipientPhone','customerNote','customerShares','quoteStatus'].forEach(id=>{$(id).oninput=()=>render(false);$(id).onchange=()=>render(false)});
loadSettings();if($('autoSharePrice').checked)$('sharePrice').value=suggested().toFixed(2);products=[blank()];renderProducts();history();render(false);
})();
