(() => {
'use strict';
const $=id=>document.getElementById(id);
const num=id=>parseFloat($(id)?.value)||0;
const integer=id=>Math.max(1,Math.floor(num(id)||1));
const fmt=(v,d=0)=>new Intl.NumberFormat('ar-EG',{maximumFractionDigits:d}).format(Number.isFinite(+v)?+v:0);
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const STORE={quotes:'barrelShare.quotes.v5',settings:'barrelShare.settings.v5',barrels:'barrelShare.barrels.v5'};
const OLD={quotes:'barrelShare.quotes.v4',settings:'barrelShare.settings.v4'};
const SETTINGS=['shippingCost','barrelResale','safetyBuffer','sharesPerBarrel','sharePrice','sarToSdg','barrelWeight','barrelVolume','minSaving','ownerWeight','ownerVolume','reserveWeight','reserveVolume','pickupPoint'];
let products=[],editing=null;

const readJson=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)??JSON.stringify(fallback))}catch{return fallback}};
const quotes=()=>readJson(STORE.quotes,[]);
const barrels=()=>readJson(STORE.barrels,[]);
function setQuotes(v){localStorage.setItem(STORE.quotes,JSON.stringify(v));renderHistory();renderKpis();renderBarrels()}
function setBarrels(v){localStorage.setItem(STORE.barrels,JSON.stringify(v));renderBarrelSelectors();renderProducts();renderBarrels();renderKpis();update(false)}

function migrate(){
  if(!localStorage.getItem(STORE.settings)&&localStorage.getItem(OLD.settings)) localStorage.setItem(STORE.settings,localStorage.getItem(OLD.settings));
  if(!localStorage.getItem(STORE.quotes)&&localStorage.getItem(OLD.quotes)){
    const old=readJson(OLD.quotes,[]).map(q=>({...q,offerMode:q.offerMode||'auto',manualOfferPrice:q.manualOfferPrice||'',offerPriceSar:q.offerPriceSar??q.totalSar??0,offerMarginSar:q.offerMarginSar??0,defaultBarrelId:q.defaultBarrelId||'',products:(q.products||[]).map(p=>({...p,barrelId:p.barrelId||''}))}));
    localStorage.setItem(STORE.quotes,JSON.stringify(old));
  }
  if(!localStorage.getItem(STORE.barrels)) localStorage.setItem(STORE.barrels,'[]');
}

const blank=()=>({id:uid('P'),name:'',url:'',qty:1,saudiPrice:0,sudanPrice:0,unitWeight:0,unitVolume:0,barrelId:''});
function saveSettings(){const s={};SETTINGS.forEach(x=>s[x]=$(x)?.value??'');s.autoSharePrice=$('autoSharePrice').checked;localStorage.setItem(STORE.settings,JSON.stringify(s))}
function loadSettings(){try{const s=readJson(STORE.settings,{});SETTINGS.forEach(x=>{if(s[x]!==undefined&&$(x))$(x).value=s[x]});if(s.autoSharePrice!==undefined)$('autoSharePrice').checked=!!s.autoSharePrice}catch{}}
function suggested(){return Math.max(0,(num('shippingCost')-num('barrelResale')+num('safetyBuffer'))/integer('sharesPerBarrel'))}
function capacity(){const d=integer('sharesPerBarrel');return{kg:Math.max(0,num('barrelWeight')-num('ownerWeight')-num('reserveWeight'))/d,l:Math.max(0,num('barrelVolume')-num('ownerVolume')-num('reserveVolume'))/d}}
function currentOffer(cost){if($('offerMode').value!=='manual')return cost;const raw=$('manualOfferPrice').value.trim();return raw===''?cost:Math.max(0,parseFloat(raw)||0)}
function calc(){
  const shares=integer('customerShares'),c=capacity();
  const productsSar=products.reduce((s,p)=>s+(+p.qty||0)*(+p.saudiPrice||0),0),sudan=products.reduce((s,p)=>s+(+p.qty||0)*(+p.sudanPrice||0),0),weight=products.reduce((s,p)=>s+(+p.qty||0)*(+p.unitWeight||0),0),volume=products.reduce((s,p)=>s+(+p.qty||0)*(+p.unitVolume||0),0);
  const shipping=shares*num('sharePrice'),cost=productsSar+shipping,offer=currentOffer(cost),landed=offer*num('sarToSdg'),margin=offer-cost,saving=sudan-landed,pct=sudan?saving/sudan*100:0,kgCap=c.kg*shares,lCap=c.l*shares;
  const weightKnown=products.some(p=>+p.unitWeight>0),volumeKnown=products.some(p=>+p.unitVolume>0),ok=(!weightKnown||weight<=kgCap)&&(!volumeKnown||volume<=lCap);
  return{shares,c,productsSar,sudan,weight,volume,shipping,cost,offer,landed,margin,saving,pct,kgCap,lCap,ok,good:sudan>0&&saving>0&&pct>=num('minSaving')&&ok,barrelsNeeded:Math.ceil(shares/integer('sharesPerBarrel'))};
}

function selectOrOther(selectId,inputId,value){const s=$(selectId),i=$(inputId);if(!s||!i)return;const has=[...s.options].some(o=>o.value===String(value)&&o.value!=='other');s.value=has?String(value):'other';i.value=value;i.classList.toggle('show',s.value==='other')}
function bindSelectOther(selectId,inputId,onChange){const s=$(selectId),i=$(inputId);if(!s||!i)return;s.addEventListener('change',()=>{i.classList.toggle('show',s.value==='other');if(s.value!=='other')i.value=s.value;onChange?.()});i.addEventListener('input',()=>onChange?.())}

function barrelOptions(selected='',inherit=false){let h=inherit?'<option value="">يتبع برميل الطلب</option>':'<option value="">غير محدد</option>';barrels().forEach(b=>h+=`<option value="${esc(b.id)}" ${b.id===selected?'selected':''}>${esc(b.id)} — ${esc(b.status)}</option>`);return h}
function renderBarrelSelectors(){const s=$('defaultBarrelId');if(!s)return;const cur=s.value;s.innerHTML=barrelOptions(cur,false);if([...s.options].some(o=>o.value===cur))s.value=cur}
function effectiveBarrel(p,quoteDefault=''){return p.barrelId||quoteDefault||''}

function quantityControl(p){const common=[1,2,3,4,5,6,10,12,24],current=String(p.qty||1),known=common.map(String).includes(current);return `<select data-qsel>${common.map(v=>`<option value="${v}" ${String(v)===current?'selected':''}>${v}</option>`).join('')}<option value="other" ${known?'':'selected'}>أخرى…</option></select><input data-f="qty" class="conditional ${known?'':'show'}" type="number" min="1" step="1" value="${p.qty||1}" inputmode="numeric">`}
function renderProducts(){
  const w=$('productsContainer');if(!w)return;w.innerHTML='';
  products.forEach((p,i)=>{
    const d=document.createElement('details');d.className='product-card';d.open=products.length===1||i===products.length-1;
    d.innerHTML=`<summary><div class="product-title"><strong>${i+1}) ${esc(p.name||'منتج جديد')}</strong><small>${p.saudiPrice?fmt(p.saudiPrice,2)+' ر.س للوحدة':'أدخل السعر للمقارنة'}</small></div><span class="product-chip">× ${fmt(p.qty)}</span></summary>
    <div class="product-body">
      <div class="product-basic"><label>اسم المنتج<input data-f="name" value="${esc(p.name)}" placeholder="مثال: حليب Anchor 1.8 كجم"></label><label>الكمية${quantityControl(p)}</label></div>
      <div class="price-row"><label>سعر الوحدة في السعودية (ر.س)<input data-f="saudiPrice" type="number" min="0" step=".01" value="${p.saudiPrice||''}" inputmode="decimal"></label><label>سعر الوحدة في السودان (ج.س)<input data-f="sudanPrice" type="number" min="0" step="1" value="${p.sudanPrice||''}" inputmode="numeric"></label></div>
      <details class="product-more"><summary>تفاصيل إضافية: البرميل، الرابط، الوزن والحجم</summary><div class="form-grid two"><label>البرميل<select data-barrel>${barrelOptions(p.barrelId,true)}</select></label><label>رابط الشراء<input data-f="url" value="${esc(p.url)}" placeholder="https://..."></label><label>وزن الوحدة (كجم)<input data-f="unitWeight" type="number" min="0" step=".01" value="${p.unitWeight||''}" inputmode="decimal"></label><label>حجم الوحدة (لتر)<input data-f="unitVolume" type="number" min="0" step=".1" value="${p.unitVolume||''}" inputmode="decimal"></label></div></details>
      <div class="remove-row"><button class="btn danger compact" data-del>حذف المنتج</button></div>
    </div>`;
    d.querySelectorAll('[data-f]').forEach(x=>x.addEventListener('input',e=>{const k=e.target.dataset.f;p[k]=['name','url'].includes(k)?e.target.value:(parseFloat(e.target.value)||0);update();updateProductHeader(d,p,i)}));
    const qsel=d.querySelector('[data-qsel]'),qinput=d.querySelector('[data-f="qty"]');qsel.addEventListener('change',()=>{qinput.classList.toggle('show',qsel.value==='other');if(qsel.value!=='other'){qinput.value=qsel.value;p.qty=+qsel.value;update();updateProductHeader(d,p,i)}});
    d.querySelector('[data-barrel]').addEventListener('change',e=>{p.barrelId=e.target.value;update(false)});
    d.querySelector('[data-del]').onclick=e=>{e.preventDefault();products=products.length===1?[blank()]:products.filter(x=>x.id!==p.id);renderProducts();update()};w.appendChild(d);
  });
  $('productsCount').textContent=`${fmt(products.length)} ${products.length===1?'منتج':'منتجات'}`;
}
function updateProductHeader(d,p,i){d.querySelector('.product-title strong').textContent=`${i+1}) ${p.name||'منتج جديد'}`;d.querySelector('.product-title small').textContent=p.saudiPrice?`${fmt(p.saudiPrice,2)} ر.س للوحدة`:'أدخل السعر للمقارنة';d.querySelector('.product-chip').textContent=`× ${fmt(p.qty)}`}

function assignedBarrelsForCurrent(){const def=$('defaultBarrelId').value;return [...new Set(products.map(p=>effectiveBarrel(p,def)).filter(Boolean))]}
function whatsapp(){
  const c=calc(),name=$('customerName').value.trim(),a=[`السلام عليكم${name?' '+name:''} 🌹`,'','حسبت ليك الطلب من السعودية إلى ود مدني:',''];
  products.filter(p=>p.name||p.saudiPrice||p.sudanPrice).forEach((p,i)=>{a.push(`${i+1}) ${p.name||'المنتج'}`,`الكمية: ${fmt(p.qty)}`);if(p.url)a.push(`الرابط: ${p.url}`);a.push('')});
  a.push(`سعر العرض النهائي: ${fmt(c.offer,2)} ر.س ≈ ${fmt(c.landed)} ج.س`);
  if(c.sudan)a.push(`سعر نفس الكمية في السودان: ${fmt(c.sudan)} ج.س`,`التوفير التقريبي: ${fmt(c.saving)} ج.س (${fmt(c.pct,1)}%)`);
  const ids=assignedBarrelsForCurrent();if(ids.length)a.push(`رقم البرميل${ids.length>1?' / البراميل':''}: ${ids.join('، ')}`);
  a.push('',`الحساب على صرف: 1 ريال = ${fmt(num('sarToSdg'))} ج.س.`,`الاستلام: ${$('pickupPoint').value}.`,'السعر النهائي يتأكد وقت الشراء وبعد تثبيت شروط شركة الشحن.');return a.join('\n');
}

function update(save=true){
  if($('autoSharePrice').checked)$('sharePrice').value=suggested().toFixed(2);if(save)saveSettings();const c=calc();
  $('productsTotalSar').textContent=`${fmt(c.productsSar,2)} ر.س`;$('shippingTotalSar').textContent=`${fmt(c.shipping,2)} ر.س`;$('costTotalSar').textContent=`${fmt(c.cost,2)} ر.س`;$('sudanTotalSdg').textContent=`${fmt(c.sudan)} ج.س`;$('offerPriceSummary').textContent=`${fmt(c.offer,2)} ر.س`;$('landedTotalSdg').textContent=`${fmt(c.landed)} ج.س`;$('offerMarginSar').textContent=`${fmt(c.margin,2)} ر.س`;
  $('manualOfferWrap').classList.toggle('show',$('offerMode').value==='manual');
  $('weightLabel').textContent=`${fmt(c.weight,1)} / ${fmt(c.kgCap,1)} كجم`;$('volumeLabel').textContent=`${fmt(c.volume,1)} / ${fmt(c.lCap,1)} لتر`;
  const wp=Math.min(100,c.kgCap?c.weight/c.kgCap*100:0),vp=Math.min(100,c.lCap?c.volume/c.lCap*100:0);$('weightBar').style.width=`${wp}%`;$('volumeBar').style.width=`${vp}%`;$('weightBar').classList.toggle('over',c.weight>c.kgCap);$('volumeBar').classList.toggle('over',c.volume>c.lCap);
  const box=$('decisionBox');if(!c.ok){box.className='decision bad';box.textContent='⚠️ الطلب أكبر من سعة الحصص المختارة.'}else if(!c.sudan){box.className='decision neutral';box.textContent='أدخل سعر السعودية وسعر السودان للمقارنة.'}else if(c.good){box.className='decision good';box.textContent=`✅ مناسب للعميل — توفير ${fmt(c.pct,1)}%`}else if(c.saving>0){box.className='decision warn';box.textContent=`⚠️ التوفير ${fmt(c.pct,1)}% فقط — أقل من الحد`}else{box.className='decision bad';box.textContent='❌ غير مناسب — الشراء في السودان أوفر'};
  let details=c.sudan?`التوفير ${fmt(c.saving)} ج.س · ${fmt(c.shares)} حصة · يحتاج تقريبًا ${fmt(c.barrelsNeeded)} ${c.barrelsNeeded===1?'برميل':'براميل'}`:'';if(c.margin<0)details+=`${details?' · ':''}⚠️ سعر العرض أقل من تكلفتك بـ ${fmt(Math.abs(c.margin),2)} ر.س`;$('decisionDetails').textContent=details;
  $('customerSharesHint').textContent=`الحصة الآن ≈ ${fmt(c.c.kg,1)} كجم / ${fmt(c.c.l,1)} لتر.`;$('settingsSummary').innerHTML=`سعة الحصة الآن <strong>${fmt(c.c.kg,1)} كجم / ${fmt(c.c.l,1)} لتر</strong> · السعر المقترح <strong>${fmt(suggested(),2)} ر.س</strong>.`;$('whatsappMessage').value=whatsapp();renderKpis();
}

function snapshot(){const c=calc(),old=editing?quotes().find(x=>x.quoteId===editing):null;return{quoteId:editing||uid('Q'),customerId:old?.customerId||uid('C'),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),customerName:$('customerName').value.trim(),customerPhone:$('customerPhone').value.trim(),recipientName:$('recipientName').value.trim(),recipientPhone:$('recipientPhone').value.trim(),pickupPoint:$('pickupPoint').value.trim(),notes:$('customerNote').value.trim(),status:$('quoteStatus').value,shares:c.shares,sharesPerBarrel:integer('sharesPerBarrel'),perShareWeightKg:c.c.kg,perShareVolumeL:c.c.l,barrelsForQuote:c.barrelsNeeded,sharePriceSar:num('sharePrice'),shippingSar:c.shipping,productsTotalSar:c.productsSar,totalSar:c.cost,sarToSdg:num('sarToSdg'),offerMode:$('offerMode').value,manualOfferPrice:$('manualOfferPrice').value,offerPriceSar:c.offer,offerMarginSar:c.margin,landedTotalSdg:c.landed,sudanMarketTotalSdg:c.sudan,savingSdg:c.saving,savingPercent:c.pct,decision:c.good?'مناسب':c.saving>0?'توفير ضعيف':'غير مناسب',totalWeightKg:c.weight,totalVolumeL:c.volume,defaultBarrelId:$('defaultBarrelId').value,products:JSON.parse(JSON.stringify(products))}}
function saveQuote(){const s=snapshot(),q=quotes(),i=q.findIndex(x=>x.quoteId===s.quoteId);if(i>=0)q[i]=s;else q.unshift(s);editing=s.quoteId;setQuotes(q);const b=$('saveQuoteBtn'),t=b.textContent;b.textContent='تم الحفظ ✓';setTimeout(()=>b.textContent=t,1000)}
function reset(){editing=null;['customerName','customerPhone','recipientName','recipientPhone','customerNote','manualOfferPrice'].forEach(x=>$(x).value='');$('quoteStatus').value='جديد';$('offerMode').value='auto';selectOrOther('customerSharesSelect','customerShares',1);$('defaultBarrelId').value='';products=[blank()];renderProducts();update(false);showTab('order')}
function openQuote(id){const q=quotes().find(x=>x.quoteId===id);if(!q)return;editing=id;$('customerName').value=q.customerName||'';$('customerPhone').value=q.customerPhone||'';$('recipientName').value=q.recipientName||'';$('recipientPhone').value=q.recipientPhone||'';$('customerNote').value=q.notes||'';$('quoteStatus').value=q.status||'جديد';$('offerMode').value=q.offerMode||'auto';$('manualOfferPrice').value=q.manualOfferPrice??(q.offerMode==='manual'?q.offerPriceSar:'');selectOrOther('customerSharesSelect','customerShares',q.shares||1);renderBarrelSelectors();$('defaultBarrelId').value=q.defaultBarrelId||'';products=q.products?.length?q.products.map(p=>({...p,id:p.id||uid('P'),barrelId:p.barrelId||''})):[blank()];renderProducts();update(false);showTab('order');window.scrollTo({top:0,behavior:'smooth'})}

function renderHistory(){const t=$('historySearch')?.value.toLowerCase()||'',rows=quotes().filter(q=>!t||`${q.customerName} ${q.customerPhone} ${(q.products||[]).map(p=>p.name).join(' ')}`.toLowerCase().includes(t)),w=$('historyContainer');if(!w)return;if(!rows.length){w.innerHTML='<div class="empty">لا توجد عروض محفوظة.</div>';return}w.innerHTML=rows.map(q=>`<div class="history-row"><div><strong>${esc(q.customerName||'بدون اسم')}</strong><small>${esc(q.customerPhone||'')}</small></div><div><strong>${fmt(q.shares)} حصة</strong><small>${esc(q.defaultBarrelId||'بدون برميل')}</small></div><div><span class="status ${q.status==='مدفوع'?'paid':q.status==='ملغي'?'cancelled':''}">${esc(q.status||'جديد')}</span></div><div><strong>${fmt(q.offerPriceSar??q.totalSar,2)} ر.س</strong><small>${esc(q.decision||'')}</small></div><div class="history-actions"><button class="btn secondary compact" data-open="${q.quoteId}">فتح</button><button class="btn danger compact" data-del="${q.quoteId}">حذف</button></div></div>`).join('');w.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openQuote(b.dataset.open));w.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('حذف هذا العرض؟'))setQuotes(quotes().filter(x=>x.quoteId!==b.dataset.del))})}
function renderKpis(){const q=quotes(),active=q.filter(x=>x.status!=='ملغي').reduce((s,x)=>s+(+x.shares||0),0);$('activeSharesKpi').textContent=fmt(active);$('barrelsNeededKpi').textContent=fmt(Math.max(barrels().length,Math.ceil(active/integer('sharesPerBarrel'))));$('quotesKpi').textContent=fmt(q.length);$('sharePriceKpi').textContent=`${fmt(num('sharePrice'),2)} ر.س`}

function nextBarrelId(){const d=new Date(),stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`,prefix=`BRL-${stamp}-`;const nums=barrels().map(b=>b.id).filter(id=>id.startsWith(prefix)).map(id=>parseInt(id.slice(prefix.length),10)||0);return `${prefix}${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
function createBarrel(){const b={id:nextBarrelId(),createdAt:new Date().toISOString(),status:'تجميع',notes:''};setBarrels([b,...barrels()]);showTab('barrels');requestAnimationFrame(()=>document.querySelector('.barrel-card')?.setAttribute('open',''))}
function barrelItems(barrelId){const out=[];quotes().filter(q=>q.status!=='ملغي').forEach(q=>(q.products||[]).forEach(p=>{if(effectiveBarrel(p,q.defaultBarrelId)===barrelId)out.push({q,p})}));return out}
function renderBarrels(){
  const w=$('barrelsContainer');if(!w)return;const bs=barrels();if(!bs.length){w.innerHTML='<div class="empty">لا توجد براميل بعد. أنشئ أول برميل ليأخذ رقمًا مميزًا.</div>';return}
  w.innerHTML=bs.map(b=>{const items=barrelItems(b.id),customers=[...new Set(items.map(x=>x.q.customerId||x.q.customerName))],weight=items.reduce((s,x)=>s+(+x.p.qty||0)*(+x.p.unitWeight||0),0),volume=items.reduce((s,x)=>s+(+x.p.qty||0)*(+x.p.unitVolume||0),0),groups=new Map();items.forEach(x=>{const k=x.q.customerId||x.q.customerName||x.q.quoteId;if(!groups.has(k))groups.set(k,{q:x.q,items:[]});groups.get(k).items.push(x.p)});let members='';groups.forEach(g=>{members+=`<div class="member-block"><div class="member-head"><div><strong>${esc(g.q.customerName||'بدون اسم')}</strong><div class="barrel-meta">${esc(g.q.customerPhone||'')} · ${fmt(g.q.shares)} حصة</div></div><button class="btn ghost compact" data-open-quote="${g.q.quoteId}">فتح الطلب</button></div><div class="member-products">${g.items.map(p=>`<div class="member-product"><strong>${esc(p.name||'منتج')}</strong><span>× ${fmt(p.qty)}</span><span>${fmt(p.unitWeight||0,2)} كجم/وحدة</span><span>${fmt(p.unitVolume||0,1)} لتر/وحدة</span></div>`).join('')}</div></div>`});
    const cls=b.status==='جاهز للشحن'?'ready':b.status==='تم الشحن'?'shipped':b.status==='وصل مدني'||b.status==='مغلق'?'arrived':'';
    return `<details class="barrel-card"><summary><div><div class="barrel-id">${esc(b.id)}</div><div class="barrel-meta">أُنشئ ${new Date(b.createdAt).toLocaleDateString('ar-EG')}</div></div><div><span class="barrel-status ${cls}">${esc(b.status)}</span></div><div><strong>${fmt(customers.length)} مشترك</strong><div class="barrel-meta">${fmt(items.length)} صنف</div></div><div class="barrel-meta">${fmt(weight,1)} كجم · ${fmt(volume,1)} لتر</div></summary><div class="barrel-body"><div class="barrel-controls"><label>الحالة<select data-barrel-status="${b.id}"><option ${b.status==='تجميع'?'selected':''}>تجميع</option><option ${b.status==='جاهز للشحن'?'selected':''}>جاهز للشحن</option><option ${b.status==='تم الشحن'?'selected':''}>تم الشحن</option><option ${b.status==='وصل مدني'?'selected':''}>وصل مدني</option><option ${b.status==='مغلق'?'selected':''}>مغلق</option></select></label><label>ملاحظة البرميل<input data-barrel-note="${b.id}" value="${esc(b.notes||'')}" placeholder="مثال: ختم رقم 123 أو موعد الشحن"></label><button class="btn danger compact" data-delete-barrel="${b.id}">حذف</button></div><div class="barrel-members">${members||'<div class="barrel-empty">لا توجد منتجات مسندة لهذا البرميل بعد.</div>'}</div></div></details>`}).join('');
  w.querySelectorAll('[data-barrel-status]').forEach(s=>s.onchange=()=>{const bs=barrels(),b=bs.find(x=>x.id===s.dataset.barrelStatus);if(b){b.status=s.value;setBarrels(bs)}});w.querySelectorAll('[data-barrel-note]').forEach(i=>i.onchange=()=>{const bs=barrels(),b=bs.find(x=>x.id===i.dataset.barrelNote);if(b){b.notes=i.value;localStorage.setItem(STORE.barrels,JSON.stringify(bs))}});w.querySelectorAll('[data-open-quote]').forEach(b=>b.onclick=e=>{e.preventDefault();openQuote(b.dataset.openQuote)});w.querySelectorAll('[data-delete-barrel]').forEach(btn=>btn.onclick=e=>{e.preventDefault();const id=btn.dataset.deleteBarrel,used=barrelItems(id).length||quotes().some(q=>q.defaultBarrelId===id);if(used){alert('لا يمكن حذف البرميل لأنه مرتبط بطلبات أو منتجات. انقلها أولًا إلى برميل آخر.');return}if(confirm(`حذف البرميل ${id}؟`))setBarrels(barrels().filter(x=>x.id!==id))})
}

function exportExcel(){
  if(typeof XLSX==='undefined'){alert('تعذر تحميل مكتبة Excel');return}const q=quotes(),bs=barrels(),settings=[['الإعداد','القيمة'],['ShippingCostSAR',num('shippingCost')],['BarrelVolumeL',num('barrelVolume')],['BarrelMaxWeightKg',num('barrelWeight')],['OwnerReservedWeightKg',num('ownerWeight')],['OwnerReservedVolumeL',num('ownerVolume')],['PackingReserveWeightKg',num('reserveWeight')],['PackingReserveVolumeL',num('reserveVolume')],['SharesPerBarrel',integer('sharesPerBarrel')],['ExpectedBarrelResaleSAR',num('barrelResale')],['SafetyBufferSAR',num('safetyBuffer')],['SharePriceSAR',num('sharePrice')],['AutoSharePrice',$('autoSharePrice').checked?'TRUE':'FALSE'],['SARToSDG',num('sarToSdg')],['MinimumSavingPercent',num('minSaving')],['PickupPoint',$('pickupPoint').value]],customers=[['CustomerID','CustomerName','WhatsApp','RecipientName','RecipientPhone','PickupPoint','Notes'],...q.map(x=>[x.customerId,x.customerName,x.customerPhone,x.recipientName,x.recipientPhone,x.pickupPoint,x.notes])],qq=[['QuoteID','CustomerID','CreatedAt','Status','Shares','SharesPerBarrel','DefaultBarrelID','OfferMode','OfferPriceSAR','OfferMarginSAR','SharePriceSAR','ShippingSAR','ProductsTotalSAR','CostTotalSAR','SARToSDG','LandedTotalSDG','SudanMarketTotalSDG','SavingSDG','SavingPercent','Decision','TotalWeightKg','TotalVolumeL'],...q.map(x=>[x.quoteId,x.customerId,x.createdAt,x.status,x.shares,x.sharesPerBarrel,x.defaultBarrelId||'',x.offerMode||'auto',x.offerPriceSar??x.totalSar,x.offerMarginSar??0,x.sharePriceSar,x.shippingSar,x.productsTotalSar,x.totalSar,x.sarToSdg,x.landedTotalSdg,x.sudanMarketTotalSdg,x.savingSdg,x.savingPercent,x.decision,x.totalWeightKg,x.totalVolumeL])],pp=[['QuoteID','ProductName','Quantity','SaudiUnitPriceSAR','SudanUnitPriceSDG','UnitWeightKg','UnitVolumeL','ProductURL','BarrelID'],...q.flatMap(x=>(x.products||[]).map(p=>[x.quoteId,p.name,p.qty,p.saudiPrice,p.sudanPrice,p.unitWeight,p.unitVolume,p.url,p.barrelId||'']))],bb=[['BarrelID','CreatedAt','Status','Notes'],...bs.map(b=>[b.id,b.createdAt,b.status,b.notes||''])];const wb=XLSX.utils.book_new();[['Settings',settings],['Customers',customers],['Quotes',qq],['Products',pp],['Barrels',bb]].forEach(([name,data])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(data),name));XLSX.writeFile(wb,`barrel-share-${new Date().toISOString().slice(0,10)}.xlsx`)
}

function showTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));if(name==='barrels')renderBarrels();if(name==='history')renderHistory();window.scrollTo({top:0,behavior:'smooth'})}
function init(){
  migrate();loadSettings();products=[blank()];renderBarrelSelectors();selectOrOther('customerSharesSelect','customerShares',num('customerShares')||1);selectOrOther('sharesPerBarrelSelect','sharesPerBarrel',num('sharesPerBarrel'));selectOrOther('minSavingSelect','minSaving',num('minSaving'));selectOrOther('pickupPointSelect','pickupPoint',$('pickupPoint').value);
  bindSelectOther('customerSharesSelect','customerShares',()=>update());bindSelectOther('sharesPerBarrelSelect','sharesPerBarrel',()=>update());bindSelectOther('minSavingSelect','minSaving',()=>update());bindSelectOther('pickupPointSelect','pickupPoint',()=>update());
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('goResultBtn').onclick=()=>{update();showTab('result')};$('editOrderBtn').onclick=()=>showTab('order');$('newQuoteBtn').onclick=reset;$('addProductBtn').onclick=()=>{products.push(blank());renderProducts();update();requestAnimationFrame(()=>document.querySelector('.product-card:last-child')?.scrollIntoView({behavior:'smooth',block:'center'}))};$('createBarrelBtn').onclick=createBarrel;
  $('copyMessageBtn').onclick=async()=>{try{await navigator.clipboard.writeText($('whatsappMessage').value);const t=$('copyMessageBtn').textContent;$('copyMessageBtn').textContent='تم النسخ ✓';setTimeout(()=>$('copyMessageBtn').textContent=t,1000)}catch{$('whatsappMessage').select();document.execCommand('copy')}};$('openWhatsappBtn').onclick=()=>{const phone=$('customerPhone').value.replace(/\D/g,''),text=encodeURIComponent($('whatsappMessage').value);window.open(phone?`https://wa.me/${phone}?text=${text}`:`https://wa.me/?text=${text}`,'_blank')};$('saveQuoteBtn').onclick=saveQuote;$('historySearch').oninput=renderHistory;$('exportBtn').onclick=exportExcel;$('importBtn').onclick=()=>$('excelFile').click();$('defaultBarrelId').onchange=()=>update(false);$('offerMode').onchange=()=>update();$('manualOfferPrice').oninput=()=>update();
  SETTINGS.forEach(id=>$(id)?.addEventListener('input',()=>update()));$('autoSharePrice').onchange=()=>update();['customerName','customerPhone','recipientName','recipientPhone','customerNote','quoteStatus'].forEach(id=>$(id)?.addEventListener('input',()=>update()));
  window.BarrelApp={importData:(settingsData,quotesData,barrelsData)=>{localStorage.setItem(STORE.settings,JSON.stringify(settingsData));localStorage.setItem(STORE.quotes,JSON.stringify(quotesData));localStorage.setItem(STORE.barrels,JSON.stringify(barrelsData||[]));location.reload()},stores:STORE};
  renderProducts();update(false);renderHistory();renderBarrels();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
